birdwikibot:
  username: #username
  token: #token

spring:
  redis:
    host: #host
    port: #port
    password: #password

time:
  schedule: 0 0 8,12,18,22 * * *
  hours: 8, 12, 18, 22

server:
  port: 8888